name: Cypress - Run E2E Page Tests
permissions:
    contents: read
    pull-requests: write

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'cypress/**'
            - 'package.json'
            - 'cypress.config.*'
    pull_request:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check-dependabot:
        runs-on: ubuntu-latest
        outputs:
            is-dependabot: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Check if PR is from Dependabot
              run: echo "Checking if actor is Dependabot - ${{ github.actor }}"

    skip-e2e-tests:
        name: Skip Cypress E2E Tests (Dependabot)
        needs: check-dependabot
        if: needs.check-dependabot.outputs.is-dependabot == 'true'
        runs-on: ubuntu-latest
        steps:
            - run: echo "🟡 Skipping Cypress tests – Dependabot PRs do not have access to secrets."

    run-e2e-tests:
        name: Run Cypress E2E Tests
        needs: check-dependabot
        if: needs.check-dependabot.outputs.is-dependabot == 'false'
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            # Use a specific commit SHA for stability
            # https://github.com/cypress-io/github-action/releases/tag/v6.10.2
            - name: Start app & run Cypress E2E Page Tests
              uses: cypress-io/github-action@b8ba51a856ba5f4c15cf39007636d4ab04f23e3c
              env:
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}
                  VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
                  VITE_BACKEND_BASE_URL: ${{ secrets.VITE_BACKEND_BASE_URL }}
                  CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
                  CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
              with:
                  start: npm run dev
                  wait-on: 'http://localhost:4000'
                  wait-on-timeout: 60
                  browser: chrome

            - name: Upload Cypress screenshots on failure
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
                  retention-days: 7

            - name: Upload Cypress videos on failure
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: cypress-videos
                  path: cypress/videos
                  retention-days: 7
