name: Run Cypress Tests

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'cypress/**'
            - 'package.json'
            - 'cypress.config.*'
    pull_request:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check-dependabot:
        runs-on: ubuntu-latest
        outputs:
            is-dependabot: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Check if PR is from Dependabot
              run: echo "Checking if actor is Dependabot - ${{ github.actor }}"

    skip-cypress:
        name: Skip Cypress Tests (Dependabot)
        needs: check-dependabot
        if: needs.check-dependabot.outputs.is-dependabot == 'true'
        runs-on: ubuntu-latest
        steps:
            - run: echo "🟡 Skipping Cypress tests – Dependabot PRs do not have access to secrets."

    run-cypress:
        name: Run Cypress Tests (Dependabot)
        needs: check-dependabot
        if: needs.check-dependabot.outputs.is-dependabot == 'false'
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Start app & run Cypress Tests
              uses: cypress-io/github-action@v6
              env:
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}
                  VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
                  VITE_BACKEND_BASE_URL: ${{ secrets.VITE_BACKEND_BASE_URL }}
                  CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
                  CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
              with:
                  start: npm run dev
                  wait-on: 'http://localhost:4000'
                  wait-on-timeout: 60
                  browser: chrome
